version: '3.8'

services:
  # Servicio principal del dashboard
  dashboard:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: home-spend-dashboard
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    env_file:
      - .env
    ports:
      - "8501:8501"  # Solo exponer localmente para desarrollo
    volumes:
      - dashboard_data:/app/data
      - dashboard_logs:/app/logs
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Proxy reverso con Nginx
  nginx:
    image: nginx:alpine
    container_name: home-spend-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Servicio para renovar certificados SSL automáticamente
  certbot:
    image: certbot/certbot
    container_name: home-spend-certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot-webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email tu-email@ejemplo.com --agree-tos --no-eff-email -d tu-dominio.com
    profiles:
      - ssl-setup  # Solo se ejecuta cuando se especifica este perfil

# Volúmenes persistentes
volumes:
  dashboard_data:
    driver: local
  dashboard_logs:
    driver: local
  nginx_cache:
    driver: local

# Red interna para comunicación entre contenedores
networks:
  dashboard-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
